### ISSUE TITLE
Error on mllm_lib build

### ISSUE THREAD

**Issue by kjh2159** [UbiquitousLearning/mllm#226]
I needed to rebuild mllm_lib.

Updated the mllm repository and rebuilt mllm_lib. However, even though I successfully built the mllm_lib around 1 month ago, an error occurs.
**_Why does this error happen and how can I fix it?_**

First of all, I built the mllm_lib in the environment of **_Ubuntu 18.04, gcc 11.4, android-ndk r27c, cmake 3.21_**.
Additionally, the following is the command I typed and the result of building

```
cmake . \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_NATIVE_API_LEVEL=android-28 \ 
-DNATIVE_LIBRARY_OUTPUT=. \
-DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3 \
-DARM=ON \
-DAPK=ON \
-DQNN=ON \
-DDEBUG=OFF \ 
-DTEST=OFF \
-DQUANT=OFF \
-DQNN_VALIDATE_NODE=ON \
-DMLLM_BUILD_XNNPACK_BACKEND=OFF
```

```
-- ARM detected
-- {fmt} version: 11.0.2
-- Build type: Release
-- current platform: Linux 
-- ARM detected
-- Build for Android APK Lib.
-- found openmp
-- ARM detected
-- found openmp
-- MLLM_QNN INCLUDES: /home/kjh2159/ondevice_LLM/mllm/src;/home/kjh2159/ondevice_LLM/mllm/include;/home/kjh2159/ondevice_LLM/mllm/third_party;/home/kjh2159/ondevice_LLM/mllm/third_party/fmt/include;/home/kjh2159/ondevice_LLM/mllm/third_party/pybind11/include;/home/kjh2159/ondevice_LLM/mllm/src/backends/qnn;/home/kjh2159/ondevice_LLM/mllm/src/backends/qnn/QNN;/home/kjh2159/ondevice_LLM/mllm/src/backends/qnn/Log;/home/kjh2159/ondevice_LLM/mllm/src/backends/qnn/PAL/include;/home/kjh2159/ondevice_LLM/mllm/src/backends/qnn/Model;/home/kjh2159/ondevice_LLM/mllm/src/backends/qnn/Utils;/home/kjh2159/ondevice_LLM/mllm/src/backends/qnn/WrapperUtils
-- found openmp
-- QNN ARM detected
-- found openmp
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kjh2159/ondevice_LLM/mllm
```

```
... skip ...
[ 91%] Building CXX object CMakeFiles/mllm_lib.dir/src/processor/PostProcess.cpp.o
[ 91%] Building CXX object CMakeFiles/mllm_lib.dir/src/processor/PreProcess.cpp.o
[ 91%] Building CXX object CMakeFiles/mllm_lib.dir/third_party/wenet_audio/feature_pipeline.cc.o
[ 91%] Building CXX object CMakeFiles/mllm_lib.dir/third_party/wenet_audio/fft.cc.o
[ 91%] Building CXX object CMakeFiles/mllm_lib.dir/src/tokenizers/Tokenizer.cpp.o
[ 91%] Building CXX object CMakeFiles/mllm_lib.dir/tools/jni/LibHelper.cpp.o
[ 91%] Building CXX object CMakeFiles/mllm_lib.dir/src/tokenizers/Unigram/Unigram.cpp.o
In file included from /home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.cpp:32:
/home/kjh2159/ondevice_LLM/mllm/src/models/phonelm/modeling_phonelm_npu.hpp:14:23: error: redefinition of 'closestFactors'
   14 | inline pair<int, int> closestFactors(int n) {
      |                       ^
/home/kjh2159/ondevice_LLM/mllm/src/models/qwen/modeling_qwen_npu.hpp:14:23: note: previous definition is here
   14 | inline pair<int, int> closestFactors(int n) {
      |                       ^
/home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.cpp:101:76: error: no member named 'setSequenceLength' in 'mllm::CPUBackend'; did you mean 'setCurSequenceLength'?
  101 |             static_cast<CPUBackend *>(Backend::global_backends[MLLM_CPU])->setSequenceLength(0);
      |                                                                            ^~~~~~~~~~~~~~~~~
      |                                                                            setCurSequenceLength
/home/kjh2159/ondevice_LLM/mllm/src/backends/cpu/CPUBackend.hpp:36:10: note: 'setCurSequenceLength' declared here
   36 |     void setCurSequenceLength(int sequence_length) {
      |          ^
/home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.cpp:149:76: error: no member named 'setSequenceLength' in 'mllm::CPUBackend'; did you mean 'setCurSequenceLength'?
  149 |             static_cast<CPUBackend *>(Backend::global_backends[MLLM_CPU])->setSequenceLength(0);
      |                                                                            ^~~~~~~~~~~~~~~~~
      |                                                                            setCurSequenceLength
/home/kjh2159/ondevice_LLM/mllm/src/backends/cpu/CPUBackend.hpp:36:10: note: 'setCurSequenceLength' declared here
   36 |     void setCurSequenceLength(int sequence_length) {
      |          ^
/home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.cpp:229:76: error: no member named 'setSequenceLength' in 'mllm::CPUBackend'; did you mean 'setCurSequenceLength'?
  229 |             static_cast<CPUBackend *>(Backend::global_backends[MLLM_CPU])->setSequenceLength(real_seq_length);
      |                                                                            ^~~~~~~~~~~~~~~~~
      |                                                                            setCurSequenceLength
/home/kjh2159/ondevice_LLM/mllm/src/backends/cpu/CPUBackend.hpp:36:10: note: 'setCurSequenceLength' declared here
   36 |     void setCurSequenceLength(int sequence_length) {
      |          ^
/home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.cpp:262:76: error: no member named 'setSequenceLength' in 'mllm::CPUBackend'; did you mean 'setCurSequenceLength'?
  262 |             static_cast<CPUBackend *>(Backend::global_backends[MLLM_CPU])->setSequenceLength(0);
      |                                                                            ^~~~~~~~~~~~~~~~~
      |                                                                            setCurSequenceLength
/home/kjh2159/ondevice_LLM/mllm/src/backends/cpu/CPUBackend.hpp:36:10: note: 'setCurSequenceLength' declared here
   36 |     void setCurSequenceLength(int sequence_length) {
      |          ^
/home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.cpp:363:76: error: no member named 'setSequenceLength' in 'mllm::CPUBackend'; did you mean 'setCurSequenceLength'?
  363 |             static_cast<CPUBackend *>(Backend::global_backends[MLLM_CPU])->setSequenceLength(real_seq_length);
      |                                                                            ^~~~~~~~~~~~~~~~~
      |                                                                            setCurSequenceLength
/home/kjh2159/ondevice_LLM/mllm/src/backends/cpu/CPUBackend.hpp:36:10: note: 'setCurSequenceLength' declared here
   36 |     void setCurSequenceLength(int sequence_length) {
      |          ^
/home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.cpp:396:76: error: no member named 'setSequenceLength' in 'mllm::CPUBackend'; did you mean 'setCurSequenceLength'?
  396 |             static_cast<CPUBackend *>(Backend::global_backends[MLLM_CPU])->setSequenceLength(0);
      |                                                                            ^~~~~~~~~~~~~~~~~
      |                                                                            setCurSequenceLength
/home/kjh2159/ondevice_LLM/mllm/src/backends/cpu/CPUBackend.hpp:36:10: note: 'setCurSequenceLength' declared here
   36 |     void setCurSequenceLength(int sequence_length) {
      |          ^
In file included from /home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.cpp:7:
In file included from /home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.hpp:8:
In file included from /home/kjh2159/Android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/memory:927:
/home/kjh2159/Android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__memory/allocator.h:165:24: error: no matching constructor for initialization of 'QWenForCausalLM_NPU'
  165 |     ::new ((void*)__p) _Up(std::forward<_Args>(__args)...);
      |                        ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kjh2159/Android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__memory/allocator_traits.h:296:9: note: in instantiation of function template specialization 'std::allocator<QWenForCausalLM_NPU>::construct<QWenForCausalLM_NPU, QWenConfig &>' requested here
  296 |     __a.construct(__p, std::forward<_Args>(__args)...);
      |         ^
/home/kjh2159/Android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__memory/shared_ptr.h:262:33: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<QWenForCausalLM_NPU>>::construct<QWenForCausalLM_NPU, QWenConfig &, void>' requested here
  262 |     allocator_traits<_TpAlloc>::construct(__tmp, __get_elem(), std::forward<_Args>(__args)...);
      |                                 ^
/home/kjh2159/Android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__memory/shared_ptr.h:818:51: note: in instantiation of function template specialization 'std::__shared_ptr_emplace<QWenForCausalLM_NPU, std::allocator<QWenForCausalLM_NPU>>::__shared_ptr_emplace<QWenConfig &, std::allocator<QWenForCausalLM_NPU>, 0>' requested here
  818 |   ::new ((void*)std::addressof(*__guard.__get())) _ControlBlock(__a, std::forward<_Args>(__args)...);
      |                                                   ^
/home/kjh2159/Android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__memory/shared_ptr.h:826:15: note: in instantiation of function template specialization 'std::allocate_shared<QWenForCausalLM_NPU, std::allocator<QWenForCausalLM_NPU>, QWenConfig &, void>' requested here
  826 |   return std::allocate_shared<_Tp>(allocator<_Tp>(), std::forward<_Args>(__args)...);
      |               ^
/home/kjh2159/ondevice_LLM/mllm/tools/jni/LibHelper.cpp:77:31: note: in instantiation of function template specialization 'std::make_shared<QWenForCausalLM_NPU, QWenConfig &, void>' requested here
   77 |             prefill_module_ = make_shared<QWenForCausalLM_NPU>(qwconfig);
      |                               ^
/home/kjh2159/ondevice_LLM/mllm/src/models/qwen/modeling_qwen_npu.hpp:532:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'QWenConfig' to 'const QWenForCausalLM_NPU' for 1st argument
  532 | class QWenForCausalLM_NPU final : public Module {
      |       ^~~~~~~~~~~~~~~~~~~
/home/kjh2159/ondevice_LLM/mllm/src/models/qwen/modeling_qwen_npu.hpp:532:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'QWenConfig' to 'QWenForCausalLM_NPU' for 1st argument
  532 | class QWenForCausalLM_NPU final : public Module {
      |       ^~~~~~~~~~~~~~~~~~~
/home/kjh2159/ondevice_LLM/mllm/src/models/qwen/modeling_qwen_npu.hpp:534:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
  534 |     QWenForCausalLM_NPU(QWenConfig &config, int chunk_size) {
      |     ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 91%] Building CXX object CMakeFiles/mllm_lib.dir/src/tokenizers/BPE/Bpe.cpp.o
8 errors generated.
make[3]: *** [CMakeFiles/mllm_lib.dir/build.make:454: CMakeFiles/mllm_lib.dir/tools/jni/LibHelper.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:273: CMakeFiles/mllm_lib.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:280: CMakeFiles/mllm_lib.dir/rule] Error 2
make: *** [Makefile:169: mllm_lib] Error 2
```

**Comment by kjh2159** [comment]
```cpp
// mllm/tools/jni/LibHelper.cpp:101
static_cast<CPUBackend *>(Backend::global_backends[MLLM_CPU])->setSequenceLength(0);
```
Should the line be changed into the following line?
```cpp
// mllm/tools/jni/LibHelper.cpp:101
static_cast<CPUBackend *>(Backend::global_backends[MLLM_CPU])->setCurSequenceLength(0);
```

At `mllm/src/backends/cpu/CPUBackend.hpp:36`, the function name is not `setSequenceLength` but `setCurSequenceLength`.
```cpp
void setCurSequenceLength(int sequence_length) {
    cur_sequence_length_ = sequence_length;
}
```

I'm not confident about if it's right though. Why does build fail even if following your team's steps...?

**Comment by oreomaker** [comment]
Thanks for your feedback. This `setSequenceLength` function has been changed to `setCurSequenceLength` in a refactor commit, which left out the android project. We will fix this as soon as possible.

**Comment by kjh2159** [comment]
@oreomaker 
Thank you for your quick respond.

**Comment by oreomaker** [comment]
I fixed the `setSequenceLength` function problems in LibHelper #227, in a previous commit, the `setTotalSequenceLength` is added which is used by HeadLinear for QNN prefilling to avoid unnecessary execution of lm_head.
As currently we have no test env due to dev-server, maybe you can fix this according to the PR #227 and verify its correctness.

**Comment by kjh2159** [comment]
Thank you for fixing it.
Tried building again, however two errors still remain. 

First of all, `closestFactors` function is redefined. So these two functions are conflicting.
```cpp
// mllm/src/models/phonelm/modeling_phonelm_npu.hpp:14:
inline pair<int, int> closestFactors(int n) 

// home/kjh2159/ondevice_LLM/mllm/src/models/qwen/modeling_qwen_npu.hpp:14
inline pair<int, int> closestFactors(int n)
```
I don't know well why two functions caused a redefinition error though...


Plus, ` error: no matching constructor for initialization of 'QWenForCausalLM_NPU'` occurs. 
The below function is provided from android ndk internally. 
```cpp
// android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__memory/allocator.h:165
::new ((void*)__p) _Up(std::forward<_Args>(__args)...);
```

However, the constructor function is not matched to the following class `QWenForCausalLM_NPU` [here](https://github.com/UbiquitousLearning/mllm/blob/main/src/models/qwen/modeling_qwen_npu.hpp#L532)
```cpp
// mllm/src/models/qwen/modeling_qwen_npu.hpp:532 
class QWenForCausalLM_NPU final : public Module {
public:
    QWenForCausalLM_NPU(QWenConfig &config, int chunk_size) {}
}
```

I guess you should initialize the object of `QWenForCasualLM_NPU` giving the `chunk_size` to fix this problem.
These issues looks  related to NPU Backend.

**Comment by oreomaker** [comment]
The LibHelper.cpp does need more fix as you mentioned. The `closestFactors` is redefined as the LibHelper includes two npu modeling file which both defined a `closestFactors` to split the chunk size to two dimensions. It should be moved to a proper place. The QWenForCasualLM_NPU constructor needs a chunk_size param.
Thanks for your feedback.

**Comment by kjh2159** [comment]
@oreomaker 
Thank you for your response. When do you plan to fix these errors?

**Comment by oreomaker** [comment]
Maybe this week, when the x86 dev environment is available.

**Comment by oreomaker** [comment]
The chunk_size in the QWenForCasualLM_NPU of LibHelper.cpp has been fixed.
